### ISSUE TITLE
Welcome message when someone joins the server

### ISSUE THREAD

**Issue by CS-5** [CS-5/biohazard-bot#1]
Message welcoming them to the server and encouraging them to use the nickname feature to set something to their first name (so we all know who people are)

**Comment by JosNun** [comment]
Any particular way you want to keep a list of users? could be something complicated like a JSON of users that stores a bunch of info on them, or something as simple as a list of user IDs.

**Comment by CS-5** [comment]
There should be a method for getting a list of users on the server or
something that triggers whenever someone joins. I'm pretty sure I remember
something about that when I looked into making a bot a while ago.

**Comment by CS-5** [comment]
Not tested, but code is finished.
